[project]
compiler = "cc"
target_name = "nur"
unity_build = false
shared = false
compile_flags = []
link_flags = ["-lm"]

[paths]
sources = [
  "src/main.c",
  "src/ast.c",
  "src/compiler.c",
  "src/lexer.c",
  "src/main.c",
  "src/fs.c",
  "src/parser.c",
  "src/source_location.c",
  "src/vm.c",
  "src/vm_gc.c",
  "src/vm_builtins.c",
  "src/vm_map.c",
  "src/vm_util.c",
]

includes = []
exclude_dirs = []
exclude_exts = []

[pkg]
deps = []
