[project]
compiler = "cc"
target_name = "nur"
unity_build = false
shared = false
compile_flags = []
link_flags = ["-lm"]

[paths]
sources = []
includes = ["src"]
exclude_dirs = [".ccls-cache"]
exclude_exts = []

[pkg]
deps = []
